  name = "somemellier"
  compatibility_date = "2025-09-02"
  compatibility_flags = ["nodejs_compat"]
  main = "@tanstack/react-start/server-entry"
  pages_build_output_dir = "dist"
  [observability]
  enabled = true
