name: Drizzle Migrations

on:
  push:
    branches: [main]

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2

      - run: bun ci

      - name: Run Drizzle migrations
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: bunx drizzle-kit migrate
